# Default Spring Profile
server:
  error:
    include-message: always

logging:
  level:
    root: INFO
    com.sportsmanagement: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

---
# for docker

spring:
  datasource:
    url: jdbc:mysql://mysql3/team-db
    username: user
    password: pwd
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none

  config:
    activate:
      on-profile: docker

  sql:
    init:
      platform: mysql
      mode: always

server.port: 8080

spring.datasource.hikari.initializationFailTimeout: 60000